theme: jekyll-theme-cayman
title: Welcome to Okey's homepage
description: Where teenagers start early ... to learn Java

collections:
  authors:

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"      
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"      
    values:
      layout: "default"
