theme: jekyll-theme-cayman
title: Welcome to Okey's homepage
description: Where teenagers start early ... to learn Java

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      
