theme: jekyll-theme-cayman
title: Welcome to Okey's blog

collections:
  authors:
    output: true
    
collections:
  topics:
    output: true
    
collections:
  chapters:
    output: true


sidebars:
- home_sidebar

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag  
  - jekyll-coffeescript  
