theme: jekyll-theme-cayman
title: Welcome to Okey's Homepage
description: ...where teenagers start learning Java

collections:
  authors:
    output: true
    
sidebars:
- home_sidebar

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      
