- name: Ladies' Shoes
  title: Awesome Shoes
  location: London
  
- name: Solar Panels
  title: Cheap energy
  location: Abuja
  
- name: Car hire
  title: Convenience redefined
  location: Lagos
  
- name: Books
  title: Reading takes you higher
  location: Lagos
