- name: Ada Fashions
  title: Awesome Shoes
  type: Ladies' Shoes
  location: London
  
- name: Frank Systems
  title: Cheap energy
  type: Solar Panels
  location: Abuja
  
- name: Chike Clothing
  title: Convenience redefined
  type: Shirts
  location: Lagos
  
- name: Uju Bookshops
  title: Reading refines you
  type: Books
  location: Lagos
