- name: Ada Fashions
  title: Awesome Shoes
  Ladies' Shoes
  location: London
  
- name: Frank Systems
  title: Cheap energy
  type: Solar Panels
  location: Abuja
  
- name: Chike Logistics
  title: Convenience redefined
  type: Car Hire
  location: Lagos
  
- name: Uju Bookshops
  title: Reading takes you higher
  type: Books
  location: Lagos
